# Jekyll configuration for Cranbury Chiropractic

# Site settings
title: "Cranbury Chiropractic"
description: "A website for Cranbury Chiropractic Center, LLC."
url: "https://cranburychiropractic.com"
baseurl: ""
og_image:
tagline: "Cranbury Chiropractic Center, LLC"
social:
  name: "Cranbury Chiropractic"
  image:
  links:
    - https://cranburychiropractic.com


# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "zen"
plugins:
  - jekyll-remote-theme
  - jekyll-data
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Meetings"
    url: "/meetings/"
  - title: "Meditation Events"
    url: "/meditation-events/"
  - title: "Resources"
    url: "/resources/"
  - title: "Buddhist Foundations"
    url: /buddhist-foundations/
  - title: "Contact"
    url: "/contact/"

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      classes: wide
      css: "custom"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
      classes: wide
      css: "custom"
  
# Markdown & formatting
markdown: kramdown
kramdown:
  input: GFM

keywords:
  - Cranbury Chiropractic
  - Chiropractic
  - Cranbury
  - Health
  - Wellness
  - Back Pain
  - Neck Pain
  - Sports Injury
  - Auto Injury
  - Massage Therapy
  - Physical Therapy
  - Rehabilitation
  - Nutrition
  - Exercise
  - Lifestyle
  - Pain Relief
  - Spinal Adjustment
  - Holistic Health
  - Alternative Medicine
  - Wellness Center
  - Family Chiropractic
  - Pediatric Chiropractic
  - Chiropractic Care
  - Chiropractic Services
  - Cranbury CT
  - Norwalk CT
  - Fairfield County
  - Connecticut Chiropractic
  - Health and Wellness
  - Injury Prevention
  - Posture Correction
  - Ergonomics
  - Health Education
  - Patient Care
  - Wellness Tips
  - Health Blog
  - Chiropractic Tips

# Exclude
exclude:
  - README.md
  - RecoveryDharmaBVT/README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - theme-temp